package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"
	"spurtcms-graphql/graph/model"
)

// UpdateChannelEntryViewCount is the resolver for the updateChannelEntryViewCount field.
func (r *mutationResolver) UpdateChannelEntryViewCount(ctx context.Context, entryID *int, slug *string) (bool, error) {
	return UpdateChannelEntryViewCount(r.DB, ctx, entryID, slug)
}

// Channellist is the resolver for the channellist field.
func (r *queryResolver) ChannelList(ctx context.Context, limit int, offset int) (*model.ChannelDetails, error) {
	return Channellist(r.DB, ctx, limit, offset)
}

// ChannelDetail is the resolver for the channelDetail field.
func (r *queryResolver) ChannelDetail(ctx context.Context, channelID *int, channelSlug *string) (*model.Channel, error) {
	return ChannelDetail(r.DB, ctx, channelID, channelSlug)
}

// ChannelEntriesList is the resolver for the channelEntriesList field.
func (r *queryResolver) ChannelEntriesList(ctx context.Context, limit int, offset int, filter *model.EntryFilter, requireData *model.RequireData) (*model.ChannelEntriesDetails, error) {
	return ChannelEntriesList(r.DB, ctx, limit, offset, filter, requireData)
}

// ChannelEntryDetail is the resolver for the channelEntryDetail field.
func (r *queryResolver) ChannelEntryDetail(ctx context.Context, categoryID *int, channelID *int, channelEntryID *int, slug *string, categoryChildID *int, profileSlug *string) (*model.ChannelEntries, error) {
	return ChannelEntryDetail(r.DB, ctx, channelID, categoryID, channelEntryID, slug, profileSlug)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
