package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"
)

// GetAwsS3Resoucres is the resolver for the getAwsS3Resoucres field.
func (r *queryResolver) GetAwsS3Resoucres(ctx context.Context, fileName string, filePath *string, width *int, height *int) (interface{}, error) {
	return GetAwsS3Resoucres(ctx, fileName, filePath, width, height)
}
