package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"
	"fmt"
	"spurtcms-graphql/graph/model"
)

// EcommerceAddToCart is the resolver for the ecommerceAddToCart field.
func (r *mutationResolver) EcommerceAddToCart(ctx context.Context, productID int, customerID int, quantity int) (bool, error) {
	panic(fmt.Errorf("not implemented: EcommerceAddToCart - ecommerceAddToCart"))
}

// EcommerceCartList is the resolver for the ecommerceCartList field.
func (r *mutationResolver) EcommerceCartList(ctx context.Context, customerID int) (*model.EcommerceCartDetails, error) {
	panic(fmt.Errorf("not implemented: EcommerceCartList - ecommerceCartList"))
}

// EcommerceProductList is the resolver for the ecommerceProductList field.
func (r *queryResolver) EcommerceProductList(ctx context.Context, limit int, offset int, filter *model.ProductFilter, sort *model.ProductSort) (*model.EcommerceProducts, error) {
	return EcommerceProductList(r.DB, ctx, limit, offset, filter, sort)
}

// EcommerceProductDetails is the resolver for the ecommerceProductDetails field.
func (r *queryResolver) EcommerceProductDetails(ctx context.Context, productID int) (*model.EcommerceProduct, error) {
	return EcommerceProductDetails(r.DB, ctx, productID)
}
