package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"
	"spurtcms-graphql/graph/model"
)

// JobApplication is the resolver for the jobApplication field.
func (r *mutationResolver) JobApplication(ctx context.Context, applicationDetails model.ApplicationInput) (bool, error) {
	return JobApplication(r.DB, ctx, applicationDetails)
}

// JobsList is the resolver for the jobsList field.
func (r *queryResolver) JobsList(ctx context.Context, limit int, offset int, filter *model.JobFilter) (*model.JobsList, error) {
	return JobsList(r.DB, ctx, limit, offset, filter)
}

// JobDetail is the resolver for the jobDetail field.
func (r *queryResolver) JobDetail(ctx context.Context, id *int, jobSlug *string) (*model.Job, error) {
	return JobDetail(r.DB, ctx, id, jobSlug)
}
