package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"
	"spurtcms-graphql/graph/model"
)

// MemberLogin is the resolver for the memberLogin field.
func (r *mutationResolver) MemberLogin(ctx context.Context, email string) (bool, error) {
	return MemberLogin(r.DB, ctx, email)
}

// VerifyMemberOtp is the resolver for the verifyMemberOtp field.
func (r *mutationResolver) VerifyMemberOtp(ctx context.Context, email string, otp int) (*model.LoginDetails, error) {
	return VerifyMemberOtp(r.DB, ctx, email, otp)
}

// MemberProfileUpdate is the resolver for the memberProfileUpdate field.
func (r *mutationResolver) MemberProfileUpdate(ctx context.Context, profiledata model.ProfileData) (bool, error) {
	return MemberProfileUpdate(r.DB, ctx, profiledata)
}

// Memberclaimnow is the resolver for the memberclaimnow field.
func (r *mutationResolver) Memberclaimnow(ctx context.Context, input model.ClaimData, profileID *int, profileSlug *string) (bool, error) {
	return Memberclaimnow(r.DB, ctx, input, profileID, profileSlug)
}

// ProfileNameVerification is the resolver for the profileNameVerification field.
func (r *mutationResolver) ProfileNameVerification(ctx context.Context, profileSlug string, profileID int) (bool, error) {
	return VerifyProfileName(r.DB, ctx, profileSlug, profileID)
}

// TemplateMemberLogin is the resolver for the templateMemberLogin field.
func (r *mutationResolver) TemplateMemberLogin(ctx context.Context, username *string, email *string, password string) (string, error) {
	return TemplateMemberLogin(r.DB, ctx, username, email, password)
}

// MemberRegister is the resolver for the memberRegister field.
func (r *mutationResolver) MemberRegister(ctx context.Context, input model.MemberDetails, ecomModule *int) (bool, error) {
	return MemberRegister(r.DB, ctx, input, ecomModule)
}

// MemberUpdate is the resolver for the memberUpdate field.
func (r *mutationResolver) MemberUpdate(ctx context.Context, memberdata model.MemberDetails) (bool, error) {
	return MemberUpdate(r.DB, ctx, memberdata)
}

// MemberPasswordUpdate is the resolver for the memberPasswordUpdate field.
func (r *mutationResolver) MemberPasswordUpdate(ctx context.Context, oldPassword string, newPassword string, confirmPassword string) (bool, error) {
	return MemberPasswordUpdate(r.DB, ctx, oldPassword, newPassword, confirmPassword)
}

// MemberProfileDetails is the resolver for the memberProfileDetails field.
func (r *queryResolver) MemberProfileDetails(ctx context.Context) (*model.MemberProfile, error) {
	return MemberProfileDetails(r.DB, ctx)
}

// GetMemberDetails is the resolver for the getMemberDetails field.
func (r *queryResolver) GetMemberDetails(ctx context.Context) (*model.Member, error) {
	return GetMemberDetails(r.DB, ctx)
}

// GetMemberProfileDetails is the resolver for the getMemberProfileDetails field.
func (r *queryResolver) GetMemberProfileDetails(ctx context.Context, id *int, profileSlug *string) (*model.MemberProfile, error) {
	return GetMemberProfileDetails(r.DB, ctx, id, profileSlug)
}
