// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type AdditionalFields struct {
	FieldID          int            `json:"fieldId" gorm:"column:id"`
	FieldName        string         `json:"fieldName"`
	FieldTypeID      int            `json:"fieldTypeId"`
	FieldTypeName    string         `json:"fieldTypeName" gorm:"column:type_name"`
	MandatoryField   int            `json:"mandatoryField"`
	OptionExist      int            `json:"optionExist"`
	CreatedOn        time.Time      `json:"createdOn"`
	CreatedBy        int            `json:"createdBy"`
	ModifiedOn       *time.Time     `json:"modifiedOn,omitempty"`
	ModifiedBy       *int           `json:"modifiedBY,omitempty"`
	IsDeleted        int            `json:"isDeleted"`
	DeletedBy        *int           `json:"deletedBy,omitempty"`
	DeletedOn        *time.Time     `json:"deletedOn,omitempty"`
	FieldDesc        string         `json:"fieldDesc"`
	OrderIndex       int            `json:"orderIndex"`
	InitialValue     *int           `json:"initialValue,omitempty"`
	Placeholder      *string        `json:"placeholder,omitempty"`
	ImagePath        string         `json:"imagePath"`
	DatetimeFormat   *string        `json:"datetimeFormat,omitempty"`
	TimeFormat       *string        `json:"timeFormat,omitempty"`
	URL              *string        `json:"url,omitempty"`
	SectionParentID  *int           `json:"sectionParentId,omitempty"`
	CharacterAllowed *int           `json:"characterAllowed,omitempty"`
	FieldValue       *FieldValue    `json:"fieldValue,omitempty" gorm:"-"`
	FieldOptions     []FieldOptions `json:"fieldOptions,omitempty" gorm:"-"`
}

type CategoriesList struct {
	Categories []TblCategory `json:"categories"`
	Count      int           `json:"count"`
}

type ChannelDetails struct {
	Channellist []TblChannel `json:"channellist"`
	Count       int          `json:"count"`
}

type ChannelEntries struct {
	ChannelEntryList []TblChannelEntries `json:"channelEntryList"`
	Count            int                 `json:"count"`
}

type ChannelEntryDetails struct {
	ChannelEntryList *ChannelEntries    `json:"channelEntryList,omitempty"`
	ChannelEntry     *TblChannelEntries `json:"channelEntry,omitempty"`
}

type FieldOptions struct {
	ID          int        `json:"id"`
	OptionName  string     `json:"optionName"`
	OptionValue string     `json:"optionValue"`
	CreatedOn   time.Time  `json:"createdOn"`
	CreatedBy   int        `json:"createdBy"`
	ModifiedOn  *time.Time `json:"modifiedOn,omitempty"`
	ModifiedBy  *int       `json:"modifiedBY,omitempty"`
	IsDeleted   int        `json:"isDeleted"`
	DeletedBy   *int       `json:"deletedBy,omitempty"`
	DeletedOn   *time.Time `json:"deletedOn,omitempty"`
}

type FieldValue struct {
	ID         int        `json:"id"`
	FieldValue string     `json:"fieldValue"`
	CreatedOn  time.Time  `json:"createdOn"`
	CreatedBy  int        `json:"createdBy"`
	ModifiedOn *time.Time `json:"modifiedOn,omitempty"`
	ModifiedBy *int       `json:"modifiedBY,omitempty"`
	DeletedBy  *int       `json:"deletedBy,omitempty"`
	DeletedOn  *time.Time `json:"deletedOn,omitempty"`
}

type LoginCredentials struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Member struct {
	ID               int           `json:"id"`
	UUID             string        `json:"uuid"`
	FirstName        string        `json:"firstName"`
	LastName         string        `json:"lastName"`
	Email            string        `json:"email"`
	MobileNo         string        `json:"mobileNo"`
	IsActive         int           `json:"isActive"`
	ProfileImage     string        `json:"profileImage"`
	ProfileImagePath string        `json:"profileImagePath"`
	LastLogin        int           `json:"lastLogin"`
	IsDeleted        int           `json:"isDeleted"`
	DeletedOn        *time.Time    `json:"deletedOn,omitempty"`
	DeletedBy        *int          `json:"deletedBy,omitempty"`
	CreatedOn        time.Time     `json:"createdOn"`
	CreatedDate      *string       `json:"createdDate,omitempty"`
	CreatedBy        int           `json:"createdBy"`
	ModifiedOn       *time.Time    `json:"modifiedOn,omitempty"`
	ModifiedBy       *int          `json:"modifiedBy,omitempty"`
	MemberGroupID    int           `json:"memberGroupId"`
	Group            []MemberGroup `json:"group,omitempty"`
	Password         string        `json:"password"`
	Username         string        `json:"username"`
	Otp              *int          `json:"otp,omitempty"`
	OtpExpiry        *time.Time    `json:"otpExpiry,omitempty"`
}

type MemberDetails struct {
	FirstName        string  `json:"firstName"`
	LastName         string  `json:"lastName"`
	Mobile           string  `json:"mobile"`
	Email            string  `json:"email"`
	Password         string  `json:"password"`
	IsActive         *int    `json:"isActive,omitempty"`
	ProfileImage     *string `json:"profileImage,omitempty"`
	ProfileImagePath *string `json:"profileImagePath,omitempty"`
	Username         *string `json:"username,omitempty"`
	GroupID          *int    `json:"groupId,omitempty"`
}

type MemberGroup struct {
	ID          int        `json:"id"`
	Name        string     `json:"name"`
	Slug        string     `json:"slug"`
	Description string     `json:"description"`
	IsActive    int        `json:"isActive"`
	IsDeleted   int        `json:"isDeleted"`
	CreatedOn   time.Time  `json:"createdOn"`
	CreatedBy   int        `json:"createdBy"`
	ModifiedOn  *time.Time `json:"modifiedOn,omitempty"`
	ModifiedBy  *int       `json:"modifiedBy,omitempty"`
	DateString  *string    `json:"dateString,omitempty"`
}

type Page struct {
	ID          int        `json:"id"`
	PageName    string     `json:"pageName"`
	Content     string     `json:"content"`
	PagegroupID int        `json:"pagegroupId"`
	OrderIndex  int        `json:"orderIndex"`
	ParentID    int        `json:"parentId"`
	Status      string     `json:"status"`
	CreatedOn   time.Time  `json:"createdOn"`
	CreatedBy   int        `json:"created_by"`
	ModifiedOn  *time.Time `json:"modifiedOn,omitempty"`
	ModifiedBy  *int       `json:"modifiedBy,omitempty"`
	IsDeleted   int        `json:"isDeleted"`
	DeletedOn   *time.Time `json:"deletedOn,omitempty"`
	DeletedBy   *int       `json:"deletedBy,omitempty"`
}

type PageAndPageGroups struct {
	Pages      []Page      `json:"pages"`
	Subpages   []SubPage   `json:"subpages"`
	Pagegroups []PageGroup `json:"pagegroups"`
}

type PageGroup struct {
	ID            int        `json:"id"`
	PagegroupName string     `json:"pagegroupName"`
	OrderIndex    int        `json:"orderIndex"`
	CreatedOn     time.Time  `json:"createdOn"`
	CreatedBy     int        `json:"created_by"`
	ModifiedOn    *time.Time `json:"modifiedOn,omitempty"`
	ModifiedBy    *int       `json:"modifiedBy,omitempty"`
	IsDeleted     int        `json:"isDeleted"`
	DeletedOn     *time.Time `json:"deletedOn,omitempty"`
	DeletedBy     *int       `json:"deletedBy,omitempty"`
}

type Space struct {
	ID               int           `json:"id"`
	SpaceName        string        `json:"spaceName"`
	SpaceSlug        string        `json:"spaceSlug"`
	SpaceDescription string        `json:"spaceDescription"`
	ImagePath        string        `json:"imagePath"`
	LanguageID       int           `json:"languageId"`
	CreatedOn        time.Time     `json:"createdOn"`
	CreatedBy        int           `json:"createdBy"`
	ModifiedOn       *time.Time    `json:"modifiedOn,omitempty"`
	ModifiedBy       *int          `json:"modifiedBy,omitempty"`
	IsDeleted        int           `json:"isDeleted"`
	DeletedOn        *time.Time    `json:"deletedOn,omitempty"`
	DeletedBy        *int          `json:"deletedBy,omitempty"`
	CategoryID       int           `json:"categoryId"`
	Categories       []TblCategory `json:"categories"`
}

type SpaceDetails struct {
	Spacelist []Space `json:"spacelist"`
	Count     int     `json:"count"`
}

type SubPage struct {
	ID          int        `json:"id"`
	SubpageName string     `json:"subpageName"`
	Conent      string     `json:"conent"`
	ParentID    int        `json:"parentId"`
	PageGroupID int        `json:"pageGroupId"`
	OrderIndex  int        `json:"orderIndex"`
	Status      string     `json:"status"`
	CreatedOn   time.Time  `json:"createdOn"`
	CreatedBy   int        `json:"created_by"`
	ModifiedOn  *time.Time `json:"modifiedOn,omitempty"`
	ModifiedBy  *int       `json:"modifiedBy,omitempty"`
	IsDeleted   int        `json:"isDeleted"`
	DeletedOn   *time.Time `json:"deletedOn,omitempty"`
	DeletedBy   *int       `json:"deletedBy,omitempty"`
}

type TblCategory struct {
	ID              int           `json:"id"`
	CategoryName    string        `json:"categoryName"`
	CategorySlug    string        `json:"categorySlug"`
	Description     string        `json:"description"`
	ImagePath       string        `json:"imagePath"`
	CreatedOn       time.Time     `json:"createdOn"`
	CreatedBy       int           `json:"createdBy"`
	ModifiedOn      *time.Time    `json:"modifiedOn,omitempty"`
	ModifiedBy      *int          `json:"modifiedBy,omitempty"`
	IsDeleted       int           `json:"isDeleted"`
	DeletedOn       *time.Time    `json:"deletedOn,omitempty"`
	DeletedBy       *int          `json:"deletedBy,omitempty"`
	ParentID        int           `json:"parentId"`
	ChildCategories []TblCategory `json:"childCategories,omitempty" gorm:"-"`
}

type TblChannel struct {
	ID                 int        `json:"id"`
	ChannelName        string     `json:"channelName"`
	ChannelDescription string     `json:"channelDescription"`
	SlugName           string     `json:"slugName"`
	FieldGroupID       int        `json:"fieldGroupId"`
	IsActive           int        `json:"isActive"`
	IsDeleted          int        `json:"isDeleted"`
	CreatedOn          time.Time  `json:"createdOn"`
	CreatedBy          int        `json:"createdBy"`
	ModifiedOn         *time.Time `json:"modifiedOn,omitempty"`
	ModifiedBy         *int       `json:"modifiedBy,omitempty"`
}

type TblChannelEntries struct {
	ID               int                `json:"id"`
	Title            string             `json:"title"`
	Slug             string             `json:"slug"`
	Description      string             `json:"description"`
	UserID           int                `json:"userId"`
	ChannelID        int                `json:"channelId"`
	Status           int                `json:"status"`
	IsActive         int                `json:"isActive"`
	IsDeleted        int                `json:"isDeleted"`
	DeletedBy        *int               `json:"deletedBy,omitempty"`
	DeletedOn        *time.Time         `json:"deletedOn,omitempty"`
	CreatedOn        time.Time          `json:"createdOn"`
	CreatedBy        int                `json:"createdBy"`
	ModifiedBy       *int               `json:"modifiedBy,omitempty"`
	ModifiedOn       *time.Time         `json:"modifiedOn,omitempty"`
	CoverImage       string             `json:"coverImage"`
	ThumbnailImage   string             `json:"thumbnailImage"`
	MetaTitle        string             `json:"metaTitle"`
	MetaDescription  string             `json:"metaDescription"`
	Keyword          string             `json:"keyword"`
	CategoriesID     string             `json:"categoriesId"`
	RelatedArticles  string             `json:"relatedArticles"`
	Categories       [][]TblCategory    `json:"categories" gorm:"-"`
	AdditionalFields []AdditionalFields `json:"additionalFields,omitempty" gorm"-"`
}
