
# GraphQL schema example
#
# https://gqlgen.com/getting-started/


scalar Upload

type Job{
    id:                  Int!
    categoriesId:        Int!
    category:          Category
    jobTitle:          String!
    jobSlug:           String!
    jobDescription:    String!
    jobLocation:       String!
    jobType:           String!
    education:         String!
    department:        String
    experience:        String
    salary:            String!
    createdOn:         Time!
    createdBy:         Int!
    isDeleted:         Int
    deletedOn:         Time
    deletedBy:         Int
    keyword:           String
    skill:             String!
    minimumYears:      Int!
    maximumYears:      Int!
    postedDate:        Time!
    validThrough:      Time!   
    status:            Int!
    modifiedOn:        Time
    modifiedBy:        Int
}

type ApplicantDetails{
    id:              Int
    jobId:           Int
    applicantId:     Int
    name:            String
    emailId:         String
    mobileNo:        String
    jobType:         String
    gender:          String
    location:        String
    education:       String
    graduation:      Int
    companyName:     String
    experience:      Int
    skills:          String
    imagePath:       String
    image:           String
    createdOn:       Time
    createdBy:       Int
    modifiedOn:      Time
    modifiedBy:      Int
    isDeleted:       Int
    deletedOn:       Time
    deletedBy:       Int
    currentSalary:   Int
    expectedSalary:  Int
    status:          Int
    resumePath:      String
    resumeName:      String
    storageType:     String
}

type JobsList{
    jobs: [Job!]!
    count: Int!
}

type applicantRegister{
    name:  String!
    emailId: String!
    mobileNo: String!
    password: String!
    createdOn : Time
    createdBy: Int
    isDeleted: Int

}


extend type Query{
    jobsList(limit:Int!,offset: Int!,filter: JobFilter) : JobsList! 
    jobDetail(Id: Int,jobSlug: String):Job!
    applicantDetails: ApplicantDetails! @auth
}

extend type Mutation{
    jobApplication(applicationDetails:applicationInput!):Boolean! @auth 
}

input applicationInput{
    name:            String!
    jobId:           Int!
    emailId:         String!
    mobileNo:        String!
    jobType:         String
    gender:          String!
    location:        String!
    education:       String!
    graduation:      Int!
    companyName:     String
    experience:      Int!
    skills:          String!
    image:           String!
    currentSalary:   Int
    expectedSalary:  Int
    resume:          String!
}

input JobFilter{
    jobTitle:          String
    jobLocation:       String
    categoryId:        Int
    categorySlug:      String
    keyWord:           String
    minimumYears:      Int
    maximumYears:      Int
    datePosted:        String
}