package controller

import "errors"

var (
	ErrInvalidMail           = errors.New("your email is not yet registered in our owndesk platform")
	ErrSendMail              = errors.New("failed to send unauthorized login attempt mail to admin")
	ErrclaimAlready          = errors.New("member profile is already claimed")
	ErrEmptyProfileSlug      = errors.New("profile slug should not be empty")
	ErrProfileSlugExist      = errors.New("profile slug already exists")
	ErrMandatory             = errors.New("missing mandatory fields")
	ErrMemberRegisterPerm    = errors.New("member register permission denied")
	ErrMemberInactive        = errors.New("inactive member")
	ErrMemberLoginPerm       = errors.New("member login permission denied")
	ErrRecordNotFound        = errors.New("record not found")
	ErrPassHash              = errors.New("hasing password failed")
	ErrUpload                = errors.New("file upload failed")
	ErrOldPass               = errors.New("old password mismatched")
	ErrConfirmPass           = errors.New("new passowrd and confirmation password mismatched")
	ErrSamePass              = errors.New("old password and new password should not be same")
	ErrLoginReq              = errors.New("login required")
	ErrUnauthorize           = errors.New("unauthorized access")
	ErrGinInstance           = errors.New("Gin instance retrieval context error")
	ErrMemberSettings        = errors.New("failed to fetch member settings")
	ErrFetchMailConfig       = errors.New("failed to fetch email configurations")
	ErrInactiveTemplate      = errors.New("mail template is inactive")
	ErrParsingHtmlTemplate   = errors.New("failed to parse the html template")
	ErrExecutingHtmlTemplate = errors.New("failed to execute html template")
	ErrNoMemberDetails       = errors.New("failed to get the member details")
	ErrNoOtpUpdate           = errors.New("unable to update otp")
	ErrFetchAdmin            = errors.New("failed to fetch the admin details")
	ErrCreatingToken         = errors.New("unable to create token")
	ErrLoginDataCheck        = errors.New("failed to get member login data")
	ErrMailExist             = errors.New("email already exists")
	ErrMobileExist           = errors.New("mobile number already exists")
	ErrFetchStorageType      = errors.New("failed to fetch the storage type details")
	ErrIllegalB64            = errors.New("illegal base64 data")
	ErrJsonUnMarshal         = errors.New("failed to unmarshall the json")
	ErrClaimMail             = errors.New("failed to send claim request mail to the admin")
	ErrClaimSubmitMail       = errors.New("failed to send claim request submission status mail to the user")
	ErrLoginClaimMail        = errors.New("current login email sholuld not be used in another claim")
	ErrLoginClaimMob         = errors.New("current login mobile number sholuld not be used in another claim")
	ErrFetchEntries          = errors.New("failed to fetch the channel Entries data")
	ErrReqApiKey             = errors.New("required api token to access graphql server")
	ErrExpireApiKey          = errors.New("graphql api token expired")
	ErrInvalidApiKey         = errors.New("invalid api token")
	ErrGetImage              = errors.New("failed to retrieve the file")
	ErrGetAwsCreds           = errors.New("failed to retrieve the aws credentials")
	ErrDecodeImg             = errors.New("failed to parse the image data")
	ErrImageResize           = errors.New("failed to resize the image")
)